### ISSUE TITLE
Needs moar SD-WAN

### ISSUE THREAD

**Issue by cdot65** [cdot65/prisma_access_ansible_collection#9]
##### ISSUE TYPE

- Feature Idea

###### panapi

n/a

###### Ansible

version 200001

###### Collection

latest

##### SUMMARY

The lack of SD-WAN is extremely disheartening

##### STEPS TO REPRODUCE

1. install Ansible Collections
2. try to do anything related to SD-WAN
3. cry

```yaml
---
- name: CREATE Tags
  hosts: prisma
  connection: local
  gather_facts: False
  become: False
  collections:
    - cdot65.prisma_access

  tasks:
    - name: CREATE tags
      cdot65.prisma_access.sdwan:
        provider:
          client_id: "{{ client_id }}"
          client_secret: "{{ client_secret }}"
          scope: "{{ scope }}"
        name: "{{ item.name }}"
        comments: "{{ item.comments }}"
        state: "present"
      loop: "{{ prisma_tags }}"

```

##### EXPECTED RESULTS

Do the SD-WAN dance

##### ACTUAL RESULTS

Ansible was upset, red wall of text.

```bash
call the whaambulance
```
